# Form implementation generated from reading ui file 'face_detection_UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Face_Detection(object):
    def setupUi(self, Face_Detection):
        Face_Detection.setObjectName("Face_Detection")
        Face_Detection.resize(860, 600)
        Face_Detection.setMinimumSize(QtCore.QSize(860, 600))
        Face_Detection.setMaximumSize(QtCore.QSize(860, 600))
        Face_Detection.setStyleSheet("QFrame {\n"
"    border: none;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=Face_Detection)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.main)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_1 = QtWidgets.QFrame(parent=self.frame)
        self.frame_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.video_label = QtWidgets.QLabel(parent=self.frame_1)
        self.video_label.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.video_label.setText("")
        self.video_label.setObjectName("video_label")
        self.verticalLayout.addWidget(self.video_label)
        self.horizontalLayout_3.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.add_prsn_btn = QtWidgets.QPushButton(parent=self.frame_3)
        self.add_prsn_btn.setStyleSheet("QPushButton {\n"
"    padding: 10px 60px;\n"
"}")
        self.add_prsn_btn.setObjectName("add_prsn_btn")
        self.verticalLayout_5.addWidget(self.add_prsn_btn)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.age_gender_btn = QtWidgets.QPushButton(parent=self.frame_4)
        self.age_gender_btn.setStyleSheet("QPushButton {\n"
"    padding: 10px 60px;\n"
"}")
        self.age_gender_btn.setObjectName("age_gender_btn")
        self.verticalLayout_6.addWidget(self.age_gender_btn)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_2.addWidget(self.frame)
        self.stackedWidget.addWidget(self.main)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.page_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 120, 80))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        Face_Detection.setCentralWidget(self.centralwidget)

        self.retranslateUi(Face_Detection)
        QtCore.QMetaObject.connectSlotsByName(Face_Detection)

    def retranslateUi(self, Face_Detection):
        _translate = QtCore.QCoreApplication.translate
        Face_Detection.setWindowTitle(_translate("Face_Detection", "Face Detection"))
        self.add_prsn_btn.setText(_translate("Face_Detection", "Add Person"))
        self.age_gender_btn.setText(_translate("Face_Detection", "Age & Gender"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Face_Detection = QtWidgets.QMainWindow()
    ui = Ui_Face_Detection()
    ui.setupUi(Face_Detection)
    Face_Detection.show()
    sys.exit(app.exec())
